name: Sphinx build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout code
    - uses: actions/checkout@v3
    # build html docs
    - name: Build HTML
      uses: ammaraskar/sphinx-action@master
    # attach html output the artifacts to the github actions job for easier inspection
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/build/html/
    # push to gh-pages branches
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
